chore: add missing return types and return statement
Light-it-labs/laravel pull request #22
Opened 2024-01-09 19:41 UTC by juantejer4

# ⚡ Add missing return types to Laravel boilerplate stubs - [86dr3nyh6](https://app.clickup.com/t/86dr3nyh6) ⚡

## 💻 What type of change is this?

- [x] 💎 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Styling
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build / CI

## ⭐ Description

I've added return types  for all stub methods, and each including a return statement

## 💬 Comments

## ✅ Checklist

- [x] This PR can be merged (it is not a draft, work in progress, or blocked on another PR)
- [ ] I have tested this change locally in multiple screen sizes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-11 18:08 UTC, gianfranco-rocco requested changes

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/controller.stub
> +            ->respond();
```suggestion
        return View::make('create');
```

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/controller.stub
> +            ->respond();
```suggestion
        return View::make('show');
```

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/controller.stub
> +    public function edit(string $id): JsonResponse
```suggestion
    public function edit(string $id): ViewContract
```

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/controller.stub
> +            ->respond();
```suggestion
        return View::make('edit');
```

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/controller.stub
> +            ->respond();
```suggestion
            ->respond(JsonResponse::HTTP_CREATED);
```

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/controller.stub
> +            ->respond();
```suggestion
            ->respond(JsonResponse::HTTP_NO_CONTENT);
```

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/factory.stub
This stub's previous return statement was right. This is the stub for factories, not controllers. Changes should be reverted.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/job.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/mail.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/markdown-mail.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/markdown-notification.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/notification.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/notification.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/policy.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/request.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/resource-collection.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/resource.stub
Revert changes.

2024-01-11 18:08 UTC, gianfranco-rocco commented on stubs/view-component.stub
Revert changes.

2024-01-15 18:15 UTC, gianfranco-rocco requested changes

2024-01-16 16:07 UTC, gianfranco-rocco commented
@sojeda I need from your experience in this PR.

2024-01-19 17:12 UTC, sojeda commented on stubs/controller.nested.singleton.api.stub
> +        App::abort(JsonResponse::HTTP_NOT_FOUND);
```
return responder()
            ->error()
            ->respond(JsonResponse::HTTP_NOT_FOUND);
```

2024-01-22 15:00 UTC, merged